/**
 * src/i18n/locales.generated.ts — AUTO-GENERATED, DO NOT EDIT.
 *
 * This file is regenerated by scripts/gen_locale_imports.py
 * from defaults/config.json. Any manual edit will be
 * overwritten at the next build.
 *
 * To add or remove a language, edit the i18n.locales
 * array in defaults/config.json and rerun the generator
 * (happens automatically in the CI workflow).
 *
 * Reference: Technical Document v1.0 — Section 10 (i18n).
 */

import enUS from "./locales/en-US.json";
import frFR from "./locales/fr-FR.json";
import deDE from "./locales/de-DE.json";
import esES from "./locales/es-ES.json";
import itIT from "./locales/it-IT.json";
import ptBR from "./locales/pt-BR.json";
import nlNL from "./locales/nl-NL.json";
import plPL from "./locales/pl-PL.json";
import ruRU from "./locales/ru-RU.json";
import ukUA from "./locales/uk-UA.json";
import trTR from "./locales/tr-TR.json";
import jaJP from "./locales/ja-JP.json";
import koKR from "./locales/ko-KR.json";
import zhCN from "./locales/zh-CN.json";
import zhTW from "./locales/zh-TW.json";
import arSA from "./locales/ar-SA.json";

// i18next resource type for each locale.
export type LocaleResource = { translation: Record<string, unknown> };

/**
 * Canonical list of supported language tags, in the order
 * they should appear in the LanguageSelector dropdown.
 * Sourced from defaults/config.json — single source of truth.
 */
export const SUPPORTED_LANGUAGES = [
  "en-US",
  "fr-FR",
  "de-DE",
  "es-ES",
  "it-IT",
  "pt-BR",
  "nl-NL",
  "pl-PL",
  "ru-RU",
  "uk-UA",
  "tr-TR",
  "ja-JP",
  "ko-KR",
  "zh-CN",
  "zh-TW",
  "ar-SA",
] as const;

export type SupportedLanguage = typeof SUPPORTED_LANGUAGES[number];

/**
 * Native-script display names for each language, shown
 * in the LanguageSelector dropdown regardless of the
 * current UI language.
 */
export const LANGUAGE_NAMES: Record<SupportedLanguage, string> = {
  "en-US": "English",
  "fr-FR": "Français",
  "de-DE": "Deutsch",
  "es-ES": "Español",
  "it-IT": "Italiano",
  "pt-BR": "Português (Brasil)",
  "nl-NL": "Nederlands",
  "pl-PL": "Polski",
  "ru-RU": "Русский",
  "uk-UA": "Українська",
  "tr-TR": "Türkçe",
  "ja-JP": "Japanese",
  "ko-KR": "Korean",
  "zh-CN": "Simplified Chinese",
  "zh-TW": "Traditional Chinese",
  "ar-SA": "Arabic",
};

/**
 * Languages written right-to-left. When one of these is
 * active, document.documentElement.dir is set to "rtl".
 */
export const RTL_LANGUAGES: ReadonlySet<SupportedLanguage> = new Set([
  "ar-SA",
]);

/**
 * Map from language tag to its loaded JSON resource,
 * ready to pass to i18next's init() function.
 */
export const LOCALE_RESOURCES: Record<SupportedLanguage, LocaleResource> = {
  "en-US": { translation: enUS },
  "fr-FR": { translation: frFR },
  "de-DE": { translation: deDE },
  "es-ES": { translation: esES },
  "it-IT": { translation: itIT },
  "pt-BR": { translation: ptBR },
  "nl-NL": { translation: nlNL },
  "pl-PL": { translation: plPL },
  "ru-RU": { translation: ruRU },
  "uk-UA": { translation: ukUA },
  "tr-TR": { translation: trTR },
  "ja-JP": { translation: jaJP },
  "ko-KR": { translation: koKR },
  "zh-CN": { translation: zhCN },
  "zh-TW": { translation: zhTW },
  "ar-SA": { translation: arSA },
};
