"""scripts/gen_locale_imports.py — Generate the TypeScript
catalog of supported locales from defaults/config.json.
Produces src/i18n/locales.generated.ts which is imported by
src/i18n/translations.ts. The generated file contains:
 - Static imports of every {tag}.json locale file
 - The SUPPORTED_LANGUAGES tuple as a union type source
 - The SupportedLanguage type alias
 - The LANGUAGE_NAMES mapping (native-script names)
 - The RTL_LANGUAGES set
 - The LOCALE_RESOURCES map used by i18next
Why a generated file instead of runtime config reading?
 TypeScript ES module imports are resolved at compile time by
 webpack/rollup/vite. You can't `import` a file whose path is
 only known at runtime. Generating the TS file at build time
 keeps the imports static (so bundling works), while still
 making the locale list config-driven: the ONLY source of
 truth is defaults/config.json.
Flow:
 1. Load and validate the i18n config via locale_config
 2. Emit the header comment explaining this is generated
 3. Emit one `import xxYy from "./locales/xx-YY.json"` line
 per locale, using a camelCase identifier derived from the
 tag (en-US → enUS, pt-BR → ptBR, ar-SA → arSA)
 4. Emit SUPPORTED_LANGUAGES as a `const` tuple
 5. Emit the SupportedLanguage type
 6. Emit LANGUAGE_NAMES as a Record
 7. Emit RTL_LANGUAGES as a ReadonlySet
 8. Emit LOCALE_RESOURCES as a Record
The file is committed to git (not gitignored) so PR reviews
can see exactly what code runs on user machines. The top of
the generated file warns "DO NOT EDIT — regenerated by
scripts/gen_locale_imports.py".
Exit codes:
 0 — file generated successfully (or content unchanged)
 3 — malformed config (LocaleConfigError)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from locale_config import LocaleConfigError, load_from_path


def tag_to_identifier(tag: str) -> str:
    """Convert a BCP 47 tag into a camelCase JavaScript
    identifier suitable for use in an ES import statement.
    Examples:
    en-US → enUS
    pt-BR → ptBR
    zh-TW → zhTW
    ar-SA → arSA
    fr → fr
    """
    parts = tag.split("-")
    if len(parts) == 1:
        return parts[0].lower()
    return parts[0].lower() + parts[1].upper()


def escape_ts_string(s: str) -> str:
    """Escape a string for safe embedding in a double-quoted
    TypeScript string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def generate(config_path: Path, output_path: Path) -> int:
    try:
        config = load_from_path(config_path)
    except LocaleConfigError as e:
        print(f"[gen-locales] config error: {e}", file=sys.stderr)
        return 3

    lines: list[str] = []

    # Header — a loud warning so nobody edits this file by hand
    lines.append("/**")
    lines.append(" * src/i18n/locales.generated.ts — AUTO-GENERATED, DO NOT EDIT.")
    lines.append(" *")
    lines.append(" * This file is regenerated by scripts/gen_locale_imports.py")
    lines.append(" * from defaults/config.json. Any manual edit will be")
    lines.append(" * overwritten at the next build.")
    lines.append(" *")
    lines.append(" * To add or remove a language, edit the i18n.locales")
    lines.append(" * array in defaults/config.json and rerun the generator")
    lines.append(" * (happens automatically in the CI workflow).")
    lines.append(" *")
    lines.append(" * Reference: Technical Document v1.0 — Section 10 (i18n).")
    lines.append(" */")
    lines.append("")

    # Static imports — one per locale, in config order
    for loc in config.locales:
        ident = tag_to_identifier(loc.tag)
        lines.append(f'import {ident} from "./locales/{loc.tag}.json";')
    lines.append("")

    # i18next Resource type
    lines.append("// i18next resource type for each locale.")
    lines.append(
        "export type LocaleResource = { translation: Record<string, unknown> };"
    )
    lines.append("")

    # SUPPORTED_LANGUAGES tuple
    lines.append("/**")
    lines.append(" * Canonical list of supported language tags, in the order")
    lines.append(" * they should appear in the LanguageSelector dropdown.")
    lines.append(" * Sourced from defaults/config.json — single source of truth.")
    lines.append(" */")
    lines.append("export const SUPPORTED_LANGUAGES = [")
    for loc in config.locales:
        lines.append(f'  "{loc.tag}",')
    lines.append("] as const;")
    lines.append("")

    lines.append("export type SupportedLanguage = typeof SUPPORTED_LANGUAGES[number];")
    lines.append("")

    # LANGUAGE_NAMES
    lines.append("/**")
    lines.append(" * Native-script display names for each language, shown")
    lines.append(" * in the LanguageSelector dropdown regardless of the")
    lines.append(" * current UI language.")
    lines.append(" */")
    lines.append("export const LANGUAGE_NAMES: Record<SupportedLanguage, string> = {")
    for loc in config.locales:
        name = escape_ts_string(loc.name)
        lines.append(f'  "{loc.tag}": "{name}",')
    lines.append("};")
    lines.append("")

    # RTL_LANGUAGES
    rtl_locales = [loc for loc in config.locales if loc.rtl]
    lines.append("/**")
    lines.append(" * Languages written right-to-left. When one of these is")
    lines.append(' * active, document.documentElement.dir is set to "rtl".')
    lines.append(" */")
    lines.append(
        "export const RTL_LANGUAGES: ReadonlySet<SupportedLanguage> = new Set(["
    )
    for loc in rtl_locales:
        lines.append(f'  "{loc.tag}",')
    lines.append("]);")
    lines.append("")

    # LOCALE_RESOURCES map
    lines.append("/**")
    lines.append(" * Map from language tag to its loaded JSON resource,")
    lines.append(" * ready to pass to i18next's init() function.")
    lines.append(" */")
    lines.append(
        "export const LOCALE_RESOURCES: Record<SupportedLanguage, LocaleResource> = {"
    )
    for loc in config.locales:
        ident = tag_to_identifier(loc.tag)
        lines.append(f'  "{loc.tag}": {{ translation: {ident} }},')
    lines.append("};")
    lines.append("")

    content = "\n".join(lines)

    # Write only if content differs — avoids spurious diffs in
    # PRs that didn't actually change the locale list
    if output_path.is_file():
        existing = output_path.read_text()
        if existing == content:
            print(f"[gen-locales] {output_path} unchanged")
            return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content)
    print(f"[gen-locales] wrote {output_path} ({len(config.locales)} locales)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate src/i18n/locales.generated.ts from "
        "the i18n section of defaults/config.json",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("defaults/config.json"),
        help="Path to defaults/config.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/i18n/locales.generated.ts"),
        help="Output path for the generated TypeScript file",
    )
    args = parser.parse_args()
    return generate(args.config, args.output)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print(f"[gen-locales] fatal: {type(e).__name__}: {e}", file=sys.stderr)
        sys.exit(2)
