/**
 * LanguageSelector — UI language dropdown.
 *
 * Reads the canonical list of supported locales from
 * `src/i18n/locales.generated.ts`, which is auto-generated by
 * `scripts/gen_locale_imports.py` from the `i18n.locales` array
 * in `defaults/config.json`. Adding or removing a language is a
 * config-only change : edit `defaults/config.json`, rerun the
 * CI generator, and this dropdown picks up the new entry on the
 * next build.
 *
 * The native-script display name (e.g. "日本語" for ja-JP) comes
 * from `LANGUAGE_NAMES`, also populated from the config — the
 * dropdown never invents a label.
 *
 * The "Auto-detect" option is added at the top in code, since it
 * doesn't correspond to a translatable locale ; its label IS
 * translated through i18next as `settings.language.auto`.
 */

import { FC, useMemo } from "react";
import { PanelSection, PanelSectionRow, Dropdown } from "@decky/ui";
import { useTranslation } from "react-i18next";

import {
  SUPPORTED_LANGUAGES,
  LANGUAGE_NAMES,
  type SupportedLanguage,
} from "../../i18n/locales.generated";
import { useLocale } from "../../contexts/LocaleContext";

const AUTO_DETECT = "auto" as const;

/** Value of the locale dropdown — every supported tag plus "auto". */
type LocaleSelection = typeof AUTO_DETECT | SupportedLanguage;

/**
 * Locale picker — lists every locale shipped under
 * `src/i18n/locales/`, sourced from the generated module so the
 * UI never drift from the DeepL translation pipeline.
 */
export const LanguageSelector: FC = () => {
  const { t } = useTranslation();
  const { locale, setLocale } = useLocale();

  // Memoise the option list — `SUPPORTED_LANGUAGES` is a
  // module-level constant, so this only runs once. The translation
  // of "Auto-detect" can change at runtime when the user switches
  // the active UI language, so we depend on `t` to re-derive it.
  const options = useMemo(
    () => [
      {
        data: AUTO_DETECT,
        label: t("settings.languageAuto", { defaultValue: "Auto-detect" }),
      },
      ...SUPPORTED_LANGUAGES.map((tag) => ({
        data: tag,
        // Native-script name. Fall back to the BCP 47 tag itself
        // if a name is missing — defensive : LANGUAGE_NAMES is
        // generated from the same source so this branch should be
        // unreachable in practice.
        label: LANGUAGE_NAMES[tag] ?? tag,
      })),
    ],
    [t],
  );

  return (
    <PanelSection title={t("settings.language")}>
      <PanelSectionRow>
        <Dropdown
          rgOptions={options}
          selectedOption={locale}
          onChange={(opt) =>
            void setLocale(String(opt.data) as LocaleSelection)
          }
        />
      </PanelSectionRow>
    </PanelSection>
  );
};
